### ISSUE TITLE
Where is the download?

### ISSUE THREAD

**Issue by sebagius7110** [ATLauncher/ATLauncher-Theme-Creator#3]
I don't know if this is in development or something, but is there a download, or would I need to compile it myself?

**Comment by gdianaty** [comment]
Self-compile. Annoyingly.

**Comment by RyanTheAllmighty** [comment]
Yeah this application is definitely out of date now and most likely wouldn't work with our new system put in place months ago.

I'll most likely just kill this repository or at minimum at least put it on the build server at https://build.atlcdn.net after the holidays.
